/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端开发风格",
  "description": "前端开发统一风格，其中包括css,html,js,框架使用等，比如class的命名，sd-home-homeTitle",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "快速上手 →",
        "actionLink": "/html/main",
        "features": [
          {
            "title": "说人话",
            "details": "围绕一个主题，绝不衍伸过多的专业术语"
          },
          {
            "title": "讲明白",
            "details": "尽量用最明白的话把一个规则说通透，方便大家开发"
          },
          {
            "title": "可传播",
            "details": "独码码不如众码码，欢迎给我提供建议，标准规则"
          }
        ],
        "footer": "SDJK Licensed | 广东赛达交通股份科技有限公司"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0e32a030",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-57f1e77b",
      "path": "/guide/"
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-3898944a",
      "path": "/config.html"
    },
    {
      "title": "js开发风格（vue）",
      "frontmatter": {},
      "regularPath": "/js/jsbase.html",
      "relativePath": "js/jsbase.md",
      "key": "v-53146660",
      "path": "/js/jsbase.html",
      "headers": [
        {
          "level": 2,
          "title": "代码末尾不加符号;",
          "slug": "代码末尾不加符号"
        },
        {
          "level": 2,
          "title": "()和{}前后要空一格",
          "slug": "和-前后要空一格"
        },
        {
          "level": 2,
          "title": "代码中的空格",
          "slug": "代码中的空格"
        }
      ]
    },
    {
      "title": "CSS开发风格（vue）",
      "frontmatter": {},
      "regularPath": "/css/base.html",
      "relativePath": "css/base.md",
      "key": "v-fdaa8e50",
      "path": "/css/base.html",
      "headers": [
        {
          "level": 2,
          "title": "全局样式",
          "slug": "全局样式"
        },
        {
          "level": 2,
          "title": "Scoped特殊属性",
          "slug": "scoped特殊属性"
        },
        {
          "level": 3,
          "title": "Scoped样式穿透",
          "slug": "scoped样式穿透"
        },
        {
          "level": 2,
          "title": "代码易读性",
          "slug": "代码易读性"
        },
        {
          "level": 2,
          "title": "不为 0 指明单位",
          "slug": "不为-0-指明单位"
        },
        {
          "level": 2,
          "title": "无属性建议整个注释或删除",
          "slug": "无属性建议整个注释或删除"
        },
        {
          "level": 2,
          "title": "属性值引号",
          "slug": "属性值引号"
        },
        {
          "level": 2,
          "title": "属性书写建议",
          "slug": "属性书写建议"
        }
      ]
    },
    {
      "title": "HTML开发风格（vue）",
      "frontmatter": {},
      "regularPath": "/html/main.html",
      "relativePath": "html/main.md",
      "key": "v-ce47e300",
      "path": "/html/main.html",
      "headers": [
        {
          "level": 2,
          "title": "标签属性",
          "slug": "标签属性"
        },
        {
          "level": 2,
          "title": "标签样式",
          "slug": "标签样式"
        },
        {
          "level": 2,
          "title": "标签缩进",
          "slug": "标签缩进"
        },
        {
          "level": 2,
          "title": "标签紧贴",
          "slug": "标签紧贴"
        },
        {
          "level": 2,
          "title": "代码嵌套",
          "slug": "代码嵌套"
        },
        {
          "level": 2,
          "title": "Class命名规则",
          "slug": "class命名规则"
        }
      ]
    },
    {
      "title": "Vue开发风格",
      "frontmatter": {},
      "regularPath": "/vue/base.html",
      "relativePath": "vue/base.md",
      "key": "v-4eafa844",
      "path": "/vue/base.html",
      "headers": [
        {
          "level": 2,
          "title": "代码结构",
          "slug": "代码结构"
        },
        {
          "level": 2,
          "title": "v-for 设置键值",
          "slug": "v-for-设置键值"
        },
        {
          "level": 2,
          "title": "v-if 和 v-for 互斥",
          "slug": "v-if-和-v-for-互斥"
        },
        {
          "level": 2,
          "title": "@click指令不能为空",
          "slug": "click指令不能为空"
        },
        {
          "level": 2,
          "title": "事件方法",
          "slug": "事件方法"
        }
      ]
    }
  ],
  "themeConfig": {
    "lastUpdated": "最后更新于",
    "repo": "https://github.com",
    "repoLabel": "Github",
    "nav": [
      {
        "text": "html",
        "link": "/html/main"
      },
      {
        "text": "CSS",
        "link": "/css/base"
      },
      {
        "text": "Javascript",
        "link": "/js/jsbase"
      },
      {
        "text": "Vue",
        "link": "/vue/base"
      },
      {
        "text": "更多",
        "items": [
          {
            "text": "没有更多啦",
            "link": ""
          }
        ]
      }
    ],
    "sidebar": {
      "/html/": [
        "main"
      ],
      "/css/": [
        "base"
      ],
      "/js/": [
        "jsbase"
      ],
      "/vue/": [
        "base"
      ]
    }
  }
}